<a href="https://colab.research.google.com/github/chavezgranados/Quantitative-Methods/blob/main/notebooks/cuaderno1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center">

<font face="gotham" color="#1B5E20"> Unidad de Posgrado de la Facultad de Economía </font>

<img src="https://yachay.digital/wp-content/uploads/2021/03/uncp.png" width="120">

<font face="gotham" color="#1B5E20"> **Curso: Métodos Cuantitativos Aplicados a la Investigación** </font>

<hr width="50%" color="#C9A227">

<font face="gotham" color="#1B5E20"> Maestría en Planificación y Proyectos de Inversión </font>

<font face="gotham" color="#1B5E20"> `Luis Chávez` </font>

<font face="gotham" color="#1B5E20"> 2026 </font>

# <font face="gotham" color="#E3B10D"> **Tópico: integración de datos**<font>

In [ ]:
#===============================================================================
# Librerías
#===============================================================================
import zipfile
import pandas as pd
import os

In [ ]:
pip install inei-microdatos

Requirement already satisfied: inei-microdatos in /usr/local/lib/python3.12/dist-packages (0.2.3)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.12/dist-packages (from inei-microdatos) (8.4.1)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from inei-microdatos) (2.2.2)
Requirement already satisfied: pyreadstat>=1.0 in /usr/local/lib/python3.12/dist-packages (from inei-microdatos) (1.3.5)
Requirement already satisfied: requests>=2.28 in /usr/local/lib/python3.12/dist-packages (from inei-microdatos) (2.32.4)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from inei-microdatos) (4.67.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->inei-microdatos) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->inei-microdatos) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->inei-microdatos) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->inei-microdatos) (2026.2)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat>=1.0->inei-microdatos) (2.22.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28->inei-microdatos) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28->inei-microdatos) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28->inei-microdatos) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28->inei-microdatos) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2->inei-microdatos) (1.17.0)

In [ ]:
import inei_microdatos

In [ ]:
from inei_microdatos import load_catalog, download_modules, read_module
from inei_microdatos.catalog import filter_catalog
catalog = load_catalog()

## **1. Fusionando módulos**

In [ ]:
enaho_2025 = filter_catalog(catalog, survey="enaho", year_min=2025, year_max=2025, period="Anual")

In [ ]:
download_modules(enaho_2025, dest="./2025", fmt="CSV")

Downloading CSV: 100%|██████████| 31/31 [00:00<00:00, 953.33it/s, fail=0, ok=0, skip=31]

{'ok': 0, 'skipped': 31, 'failed': 0, 'bad_zip': 0}

In [ ]:
def leer_enaho(zip_file, tabla):

    with zipfile.ZipFile(zip_file) as z:
        archivo = next(f for f in z.namelist()
            if tabla in f)
        return pd.read_csv(
            z.open(archivo),
            sep=";",
            encoding="latin1",
            low_memory=False)
base = "./2025/Condiciones de Vida y Pobreza - ENAHO/2025/Anual - (Ene-Dic)"

In [ ]:
# Módulo 200
mod200 = leer_enaho(f"{base}/1031-Modulo02.zip", "Enaho01-2025-200")
mod200.head()

,AÑO,MES,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO,DOMINIO,ESTRATO,P201P,...,P213,P214,P215,P216,P217,T211,TICUEST01,FACPOB07,NCONGLOME,SUB_CONGLOME
0,2025,1,15009,12,11,1,10101,4,4,20250150090121101,...,1,1,,,,,2,"87,2856903076172",7098,0
1,2025,1,15009,12,11,2,10101,4,4,20250150090121102,...,2,2,,,,,2,"87,2856903076172",7098,0
2,2025,1,15009,25,11,1,10101,4,4,20250150090251101,...,1,1,,,,,2,"87,2856903076172",7098,0
3,2025,1,15009,25,11,2,10101,4,4,20250150090251102,...,2,2,,,,,2,"87,2856903076172",7098,0
4,2025,1,15009,25,11,3,10101,4,4,20250150090251103,...,3,3,,,,,2,"87,2856903076172",7098,0

In [ ]:
# Módulo 300
mod300 = leer_enaho(f"{base}/1031-Modulo03.zip", "Enaho01A-2025-300")
mod300.head()

,AÑO,MES,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO,DOMINIO,ESTRATO,CODINFOR,...,I311D$5,I311D$6,I311D$7,I3121C,I3122C,I315B,FACTOR07,FACTORA07,NCONGLOME,SUB_CONGLOME
0,2025,1,15009,12,11,1,10101,4,4,1,...,,,351,,,,"87,2856903076172","150,298141479492",7098,0
1,2025,1,15009,12,11,2,10101,4,4,2,...,,,,,,,"87,2856903076172","125,093391418457",7098,0
2,2025,1,15009,25,11,1,10101,4,4,1,...,,,,,,,"87,2856903076172","127,413833618164",7098,0
3,2025,1,15009,25,11,2,10101,4,4,2,...,,,,,,,"87,2856903076172","98,0374298095703",7098,0
4,2025,1,15009,25,11,3,10101,4,4,3,...,,,,,,,"87,2856903076172","93,3369903564453",7098,0

In [ ]:
# Módulo 400
mod400 = leer_enaho(f"{base}/1031-Modulo04.zip", "Enaho01A-2025-400")
mod400.head()

,AÑO,MES,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO,DOMINIO,ESTRATO,CODINFOR,...,I41810,I41811,I41812,I41813,I41814,I41815,I41816,FACTOR07,NCONGLOME,SUB_CONGLOME
0,2025,1,15009,12,11,1,10101,4,4,1,...,,,,,,,,"87,2856903076172",7098,0
1,2025,1,15009,12,11,2,10101,4,4,2,...,,,,,,,,"87,2856903076172",7098,0
2,2025,1,15009,25,11,1,10101,4,4,1,...,,,,,,,,"87,2856903076172",7098,0
3,2025,1,15009,25,11,2,10101,4,4,2,...,,56,,,,,,"87,2856903076172",7098,0
4,2025,1,15009,25,11,3,10101,4,4,3,...,,,,,,,,"87,2856903076172",7098,0

In [ ]:
mod200.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115145 entries, 0 to 115144
Data columns (total 40 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AÑO           115145 non-null  int64
 1   MES           115145 non-null  int64
 2   CONGLOME      115145 non-null  int64
 3   VIVIENDA      115145 non-null  int64
 4   HOGAR         115145 non-null  int64
 5   CODPERSO      115145 non-null  int64
 6   UBIGEO        115145 non-null  int64
 7   DOMINIO       115145 non-null  int64
 8   ESTRATO       115145 non-null  int64
 9   P201P         115145 non-null  int64
 10  P203          115145 non-null  int64
 11  P203A         115145 non-null  object
 12  P203B         115145 non-null  object
 13  P204          115145 non-null  object
 14  P205          115145 non-null  object
 15  P206          115145 non-null  object
 16  P207          115145 non-null  object
 17  P208A         115145 non-null  object
 18  P208B         115145 non-null  object
 19  P209          115145 non-null  object
 20  P210          115145 non-null  object
 21  P211A         115145 non-null  object
 22  P211D         115145 non-null  object
 23  OCUPAC_R3     115145 non-null  object
 24  OCUPAC_R4     115145 non-null  object
 25  RAMA_R3       115145 non-null  object
 26  RAMA_R4       115145 non-null  object
 27  CODTAREA      115145 non-null  object
 28  CODTIEMPO     115145 non-null  object
 29  P212          115145 non-null  object
 30  P213          115145 non-null  object
 31  P214          115145 non-null  object
 32  P215          115145 non-null  object
 33  P216          115145 non-null  object
 34  P217          115145 non-null  object
 35  T211          115145 non-null  object
 36  TICUEST01     115145 non-null  int64
 37  FACPOB07      115145 non-null  object
 38  NCONGLOME     115145 non-null  int64
 39  SUB_CONGLOME  115145 non-null  int64
dtypes: int64(14), object(26)
memory usage: 35.1+ MB

In [ ]:
mod200_300 = pd.merge(mod200, mod300, on=["CONGLOME", "VIVIENDA", "HOGAR", "CODPERSO"], how="inner")
mod200_300.head()

,AÑO_x,MES_x,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO_x,DOMINIO_x,ESTRATO_x,P201P,...,I311D$5,I311D$6,I311D$7,I3121C,I3122C,I315B,FACTOR07,FACTORA07,NCONGLOME_y,SUB_CONGLOME_y
0,2025,1,15009,12,11,1,10101,4,4,20250150090121101,...,,,351,,,,"87,2856903076172","150,298141479492",7098,0
1,2025,1,15009,12,11,2,10101,4,4,20250150090121102,...,,,,,,,"87,2856903076172","125,093391418457",7098,0
2,2025,1,15009,25,11,1,10101,4,4,20250150090251101,...,,,,,,,"87,2856903076172","127,413833618164",7098,0
3,2025,1,15009,25,11,2,10101,4,4,20250150090251102,...,,,,,,,"87,2856903076172","98,0374298095703",7098,0
4,2025,1,15009,25,11,3,10101,4,4,20250150090251103,...,,,,,,,"87,2856903076172","93,3369903564453",7098,0

In [ ]:
mod200.shape, mod300.shape, mod200_300.shape

((115145, 40), (104446, 495), (104446, 531))

In [ ]:
datos = pd.merge(mod200_300, mod400, on=["CONGLOME", "VIVIENDA", "HOGAR", "CODPERSO"], how="inner")
datos.head()

,AÑO_x,MES_x,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO_x,DOMINIO_x,ESTRATO_x,P201P,...,I41810,I41811,I41812,I41813,I41814,I41815,I41816,FACTOR07_y,NCONGLOME,SUB_CONGLOME
0,2025,1,15009,12,11,1,10101,4,4,20250150090121101,...,,,,,,,,"87,2856903076172",7098,0
1,2025,1,15009,12,11,2,10101,4,4,20250150090121102,...,,,,,,,,"87,2856903076172",7098,0
2,2025,1,15009,25,11,1,10101,4,4,20250150090251101,...,,,,,,,,"87,2856903076172",7098,0
3,2025,1,15009,25,11,2,10101,4,4,20250150090251102,...,,56,,,,,,"87,2856903076172",7098,0
4,2025,1,15009,25,11,3,10101,4,4,20250150090251103,...,,,,,,,,"87,2856903076172",7098,0

In [ ]:
mod200_300.shape, mod400.shape, datos.shape

((104446, 531), (107802, 884), (104446, 1411))

## **2. Fusionando años**

In [ ]:
enaho = filter_catalog(catalog, survey="enaho", year_min=2023, year_max=2025, period="Anual")
download_modules(enaho, dest="./enaho", fmt="CSV")

Downloading CSV: 100%|██████████| 103/103 [01:31<00:00,  1.13it/s, fail=0, ok=103, skip=0]

{'ok': 103, 'skipped': 0, 'failed': 0, 'bad_zip': 0}

In [ ]:
base1 = "/content/enaho/Condiciones de Vida y Pobreza - ENAHO"

In [ ]:
def leer_enaho(zip_file, tabla):
    with zipfile.ZipFile(zip_file) as z:
        archivo = next(
            f for f in z.namelist()
            if tabla in f)
        return pd.read_csv(z.open(archivo),
            sep=None, # autodetecta delimitador
            engine="python",
            encoding="latin1")

In [ ]:
for anio in range(2023, 2026):
    carpeta = f"{base1}/{anio}/Anual - (Ene-Dic)"
    zip_mod02 = next(
        os.path.join(carpeta, f)
        for f in os.listdir(carpeta)
        if "Modulo02.zip" in f)
    df = leer_enaho(zip_mod02,
        f"Enaho01-{anio}-200")
    print(anio, df.shape)

2023 (119747, 40)
2024 (117721, 40)
2025 (115145, 40)

In [ ]:
lista = []
for anio in range(2023, 2026):
    carpeta = f"{base1}/{anio}/Anual - (Ene-Dic)"
    zip_mod02 = next(
        os.path.join(carpeta, f)
        for f in os.listdir(carpeta)
        if "Modulo02.zip" in f)
    df = leer_enaho(zip_mod02,
        f"Enaho01-{anio}-200")
    df["anio"] = anio
    lista.append(df)
panel200 = pd.concat(lista, ignore_index=True)
print(panel200.shape)

(352613, 41)

In [ ]:
panel200

,AÑO,MES,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO,DOMINIO,ESTRATO,P201P,...,OCUPAC_R4,RAMA_R3,RAMA_R4,CODTAREA,CODTIEMPO,TICUEST01,FACPOB07,NCONGLOME,SUB_CONGLOME,anio
0,2023,2,5007,22,11,1,10101,4,4,20190050070221101,...,,,,,,2,50.466671,7070,0,2023
1,2023,2,5007,22,11,2,10101,4,4,20190050070221102,...,,,,,,2,50.466671,7070,0,2023
2,2023,2,5007,22,11,3,10101,4,4,20190050070221104,...,,,,,,2,50.466671,7070,0,2023
3,2023,2,5007,31,11,1,10101,4,4,20190050070311102,...,,,,,,2,50.466671,7070,0,2023
4,2023,2,5007,31,11,2,10101,4,4,20230050070311102,...,,,,,,2,50.466671,7070,0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352608,2025,12,20859,79,11,1,230109,3,5,20250208590791101,...,,,,,,2,"29,9040966033936",51509,0,2025
352609,2025,12,20859,79,11,2,230109,3,5,20250208590791102,...,,,,,,2,"29,9040966033936",51509,0,2025
352610,2025,12,20859,79,11,3,230109,3,5,20250208590791103,...,9211,111,111,1,0,2,"29,9040966033936",51509,0,2025
352611,2025,12,20859,79,11,4,230109,3,5,20250208590791104,...,9211,111,111,1,1,2,"29,9040966033936",51509,0,2025
352612,2025,12,20859,91,11,1,230109,3,5,20250208590911101,...,,,,,,2,"29,9040966033936",51509,0,2025